<?php
    $host = "host_hidden"; // For obvious reasons, it's hidden.
    $user = "user_hidden"; // For obvious reasons, it's hidden.
    $password = "password_hidden"; // For obvious reasons, it's hidden.
    $dbname = "dbname_hidden"; // For obvious reasons, it's hidden.
    
    $connection = new mysqli($host, $user, $password, $dbname);

    $query = $connection -> query("SELECT * FROM Products ORDER BY ID ASC;");
                
    while($row = mysqli_fetch_assoc($query)) {
?>

    <div class="card custom_card text-center">
        <input class="form-check-input ms-2 mt-2 delete-checkbox" type="checkbox" value="" id="flexCheckDefault"/>
        <div class="card-body mb-3">
            <div class="sku_div"><?= $row["SKU"] ?></div>
            <div><?= $row["Name"] ?></div>
            <div><?= $row["Price"] , " $" ?></div>
            <div><?= $row["AttributesName"] . ": " . $row["Attributes"] . " " . $row["AttributesUnit"] ?></div>
        </div>
    </div>

<?php
    }
?>